data:
    lmdb_path: /mnt/fast/nobackup/scratch4weeks/sa04359/data/lmdb-4
    max_length: 300
    labels: ./data/labels
model:
    tokenizer: /mnt/fast/nobackup/scratch4weeks/sa04359/MBart_trimmed
    transformer: /mnt/fast/nobackup/scratch4weeks/sa04359/MBart_trimmed
    resnet: /mnt/fast/nobackup/scratch4weeks/sa04359/resnet18.pth
    dino: /mnt/fast/nobackup/scratch4weeks/sa04359/dino/tmp.pth
    embed_dim: 1024
    sign_proj: True
training:
    wandb: disabled # online or disabled
    scale_embedding: False
    ckpt_path: /home/sobhan/Documents/Code/MLLM/outputs/run_2025-01-23_00-29-19/best-epoch=081-val_total_loss=0.964.ckpt
    ckpt_path_landa=0.5: /home/sobhan/Documents/Code/MLLM/outputs/run_2025-01-21_01-22-53/best-epoch=085-val_loss=0.000.ckpt
    ckpt_path_old: /home/sobhan/Documents/Code/MLLM/outputs/run_2024-12-29_18-57-45/best-epoch=010-val_loss=0.605.ckpt
    ckpt_path_shit_result_multi_stage: /home/sobhan/Documents/Code/MLLM/ckpts/best-epoch=089-val_loss=3.722-val_bleu=14.258.ckpt
    ckpt_path_best: /mnt/fast/nobackup/scratch4weeks/sa04359/MMSLT/run_2024-12-10_17-56-53/best-epoch=076-val_loss=1.120.ckpt
save:
    output: outputs
    csv: csv_outputs/